forge 'forge.puppetlabs.com'

mod 'puppet-r10k', '12.1.1'
mod 'puppetlabs-apt', '9.1.0'
mod 'puppetlabs-concat', '9.0.0'
mod 'puppetlabs-firewall', '7.0.2'
mod 'puppetlabs-inifile', '6.1.0'
mod 'puppetlabs-postgresql', '10.0.2'
mod 'puppetlabs-puppet_agent', '4.16.0'
mod 'puppetlabs-puppetdb', '7.13.0'
mod 'puppetlabs-stdlib', '9.4.1'
mod 'puppetlabs-transition', '2.0.0'
mod 'puppetlabs-vcsrepo', '6.1.0'
