forge 'forge.puppetlabs.com'

mod 'puppet/r10k', '12.2.0'
mod 'puppetlabs/apt', '9.4.0'
mod 'aursu/bsys', '0.6.3'
mod 'puppetlabs/concat', '9.0.2'
mod 'puppetlabs/firewall', '6.0.0'
mod 'puppetlabs/inifile', '6.1.0'
mod 'choria/mcollective', '0.14.5'
mod 'aursu/openssh', '0.9.4'
mod 'puppetlabs/postgresql', '9.2.0'
mod 'puppetlabs/puppet_agent', '4.18.0'
mod 'puppetlabs/stdlib', '9.4.1'
mod 'puppet/systemd', '5.2.0'
mod 'puppetlabs/transition', '2.0.0'
mod 'puppetlabs/vcsrepo', '6.1.0'
